-- Insert 100 employees with random last names
INSERT INTO employees (employee_last_name) VALUES
('Smith'), ('Johnson'), ('Williams'), ('Brown'), ('Jones'), ('Garcia'), ('Miller'), ('Davis'), ('Rodriguez'), ('Martinez'),
('Hernandez'), ('Lopez'), ('Gonzalez'), ('Wilson'), ('Anderson'), ('Thomas'), ('Taylor'), ('Moore'), ('Jackson'), ('Martin'),
('Lee'), ('Perez'), ('Thompson'), ('White'), ('Harris'), ('Sanchez'), ('Clark'), ('Ramirez'), ('Lewis'), ('Robinson'),
('Walker'), ('Young'), ('Allen'), ('King'), ('Wright'), ('Scott'), ('Torres'), ('Nguyen'), ('Hill'), ('Flores'),
('Green'), ('Adams'), ('Nelson'), ('Baker'), ('Hall'), ('Rivera'), ('Campbell'), ('Mitchell'), ('Carter'), ('Roberts'),
('Gomez'), ('Phillips'), ('Evans'), ('Turner'), ('Diaz'), ('Parker'), ('Cruz'), ('Edwards'), ('Collins'), ('Reyes'),
('Stewart'), ('Morris'), ('Morales'), ('Murphy'), ('Cook'), ('Rogers'), ('Gutierrez'), ('Ortiz'), ('Morgan'), ('Cooper'),
('Peterson'), ('Bailey'), ('Reed'), ('Kelly'), ('Howard'), ('Ramos'), ('Kim'), ('Cox'), ('Ward'), ('Richardson'),
('Watson'), ('Brooks'), ('Chavez'), ('Wood'), ('James'), ('Bennett'), ('Gray'), ('Mendoza'), ('Ruiz'), ('Hughes'),
('Price'), ('Alvarez'), ('Castillo'), ('Sanders'), ('Patel'), ('Myers'), ('Long'), ('Ross'), ('Foster'), ('Jimenez');

-- Insert 100 notes linked to random employees
INSERT INTO notes (content, employee_id) VALUES
('Completed project A', 1), ('Meeting with client', 2), ('Performance review scheduled', 3),
('Submitted report on time', 4), ('Teamwork appreciated', 5), ('New software training needed', 6),
('Handled customer complaint well', 7), ('Suggested workflow improvement', 8), ('Late submission warning', 9),
('Excellent communication skills', 10), ('Training completed successfully', 11), ('Improved sales by 15%', 12),
('Missed deadline, needs follow-up', 13), ('Great leadership in crisis', 14), ('Exceeded sales targets', 15),
('Needs improvement in punctuality', 16), ('Handled extra workload efficiently', 17), ('Proactive in team meetings', 18),
('Received positive customer feedback', 19), ('Lack of attention to detail', 20), ('Volunteered for extra tasks', 21),
('Follow-up needed on project X', 22), ('Conducted training session', 23), ('Created detailed report', 24),
('Led important presentation', 25), ('Resolved technical issue', 26), ('Assisted new employees', 27),
('Overcame a major challenge', 28), ('Suggested cost-saving measures', 29), ('Provided useful market insights', 30),
('Improved department workflow', 31), ('Met all deadlines this quarter', 32), ('Exceptional work ethic', 33),
('Took initiative in crisis', 34), ('Achieved high customer ratings', 35), ('Worked overtime when required', 36),
('Helped organize corporate event', 37), ('Critical thinking praised', 38), ('Self-motivated and dedicated', 39),
('Found innovative solutions', 40), ('Supported junior colleagues', 41), ('Strong analytical skills', 42),
('Resolved client dispute', 43), ('Exceeded KPIs for the quarter', 44), ('Improved team coordination', 45),
('Highly adaptable to changes', 46), ('Good at conflict resolution', 47), ('Timely execution of tasks', 48),
('Mentored a new hire', 49), ('Demonstrated strong leadership', 50), ('Needs improvement in time management', 51),
('Suggested better documentation process', 52), ('Contributed to major project success', 53), ('Helped reduce errors', 54),
('Strong work ethic and discipline', 55), ('Assisted in strategic planning', 56), ('Collaborated effectively', 57),
('Handled urgent client request', 58), ('Reduced costs in department', 59), ('Reliable team member', 60),
('Effective multitasking skills', 61), ('Great at knowledge sharing', 62), ('Encouraged team morale', 63),
('Took on additional responsibilities', 64), ('Showed exceptional creativity', 65), ('Enhanced customer engagement', 66),
('Optimized internal processes', 67), ('Successfully led negotiations', 68), ('Good delegation skills', 69),
('Handled unexpected challenges', 70), ('Pioneered a new approach', 71), ('Suggested IT infrastructure improvements', 72),
('Recommended best practices', 73), ('Analyzed business trends', 74), ('Strong technical expertise', 75),
('Ensured compliance with regulations', 76), ('Highly dependable and efficient', 77), ('Solved a major problem', 78),
('Assisted in recruitment process', 79), ('Good eye for details', 80), ('Completed a certification course', 81),
('Showed initiative in learning', 82), ('Valuable asset to the team', 83), ('Worked well under pressure', 84),
('Gave valuable customer insights', 85), ('Enhanced security measures', 86), ('Supported cross-functional teams', 87),
('Led a major innovation project', 88), ('Identified potential risks', 89), ('Maintained high quality of work', 90),
('Provided excellent documentation', 91), ('Improved data management', 92), ('Proactive in suggesting ideas', 93),
('Highly organized and efficient', 94), ('Assisted with risk assessment', 95), ('Developed a training manual', 96),
('Committed to continuous improvement', 97), ('Managed workload effectively', 98), ('Suggested cost-cutting ideas', 99),
('Collaborated well across teams', 100);
