INSERT INTO users (username, password) VALUES 
('user1', 'password1'),
('user2', 'password2'),
('user3', 'password3'),
('user4', 'password4'),
('user5', 'password5'),
('user6', 'password6'),
('user7', 'password7'),
('user8', 'password8'),
('user9', 'password9'),
('user10', 'password10');

INSERT INTO customers (first_name, last_name, street, house_no, post_code, city, email, created_by) VALUES
('John', 'Doe', 'Main Street', '1A', 1234, 'Springfield', 'john.doe1@example.com', 1),
('Jane', 'Smith', 'Second Ave', '22B', 4321, 'Riverdale', 'jane.smith2@example.com', 2),
('Bob', 'Johnson', 'Elm Street', '5C', 1010, 'Gotham', 'bob.johnson3@example.com', 3),
('Alice', 'Williams', 'Oak Road', '3D', 2020, 'Metropolis', 'alice.williams4@example.com', 4),
('Tom', 'Brown', 'Maple Lane', '4E', 3030, 'Star City', 'tom.brown5@example.com', 5),
('Emma', 'Jones', 'Pine Blvd', '6F', 4040, 'Central City', 'emma.jones6@example.com', 6),
('Luke', 'Miller', 'Birch Dr', '7G', 5050, 'Smallville', 'luke.miller7@example.com', 7),
('Olivia', 'Davis', 'Cedar Ct', '8H', 6060, 'Coast City', 'olivia.davis8@example.com', 8),
('Liam', 'Wilson', 'Ash St', '9I', 7070, 'Hill Valley', 'liam.wilson9@example.com', 9),
('Sophia', 'Moore', 'Fir Way', '10J', 8080, 'Neo Tokyo', 'sophia.moore10@example.com', 10),

('Noah', 'Taylor', 'Palm Street', '11A', 1111, 'Liberty City', 'noah.taylor11@example.com', 1),
('Ava', 'Anderson', 'Sunset Blvd', '12B', 2222, 'Los Santos', 'ava.anderson12@example.com', 2),
('James', 'Thomas', 'Broadway', '13C', 3333, 'Vice City', 'james.thomas13@example.com', 3),
('Isabella', 'Jackson', '5th Ave', '14D', 4444, 'Raccoon City', 'isabella.jackson14@example.com', 4),
('Logan', 'White', '6th Street', '15E', 5555, 'San Fierro', 'logan.white15@example.com', 5),
('Mia', 'Harris', '7th Blvd', '16F', 6666, 'Las Venturas', 'mia.harris16@example.com', 6),
('Elijah', 'Martin', '8th Dr', '17G', 7777, 'Elwood City', 'elijah.martin17@example.com', 7),
('Amelia', 'Thompson', '9th Ct', '18H', 8888, 'Quahog', 'amelia.thompson18@example.com', 8),
('Benjamin', 'Garcia', '10th St', '19I', 9999, 'Springfield', 'benjamin.garcia19@example.com', 9),
('Charlotte', 'Martinez', '11th Way', '20J', 1212, 'Riverdale', 'charlotte.martinez20@example.com', 10),

('Daniel', 'Robinson', 'Maple St', '21A', 1313, 'Gotham', 'daniel.robinson21@example.com', 1),
('Evelyn', 'Clark', 'Cherry Ave', '22B', 1414, 'Metropolis', 'evelyn.clark22@example.com', 2),
('Matthew', 'Rodriguez', 'Willow Rd', '23C', 1515, 'Star City', 'matthew.rodriguez23@example.com', 3),
('Abigail', 'Lewis', 'Spruce Blvd', '24D', 1616, 'Central City', 'abigail.lewis24@example.com', 4),
('Jackson', 'Lee', 'Poplar Dr', '25E', 1717, 'Smallville', 'jackson.lee25@example.com', 5),
('Harper', 'Walker', 'Hickory Ct', '26F', 1818, 'Coast City', 'harper.walker26@example.com', 6),
('Sebastian', 'Hall', 'Juniper St', '27G', 1919, 'Hill Valley', 'sebastian.hall27@example.com', 7),
('Ella', 'Allen', 'Magnolia Way', '28H', 2022, 'Neo Tokyo', 'ella.allen28@example.com', 8),
('Aiden', 'Young', 'Dogwood Lane', '29I', 2121, 'Liberty City', 'aiden.young29@example.com', 9),
('Scarlett', 'Hernandez', 'Palm Ct', '30J', 2222, 'Los Santos', 'scarlett.hernandez30@example.com', 10),

('Henry', 'King', 'Aspen St', '31A', 2323, 'Vice City', 'henry.king31@example.com', 1),
('Aria', 'Wright', 'Redwood Ave', '32B', 2424, 'Raccoon City', 'aria.wright32@example.com', 2),
('Wyatt', 'Lopez', 'Linden Blvd', '33C', 2525, 'San Fierro', 'wyatt.lopez33@example.com', 3),
('Grace', 'Hill', 'Sycamore Dr', '34D', 2626, 'Las Venturas', 'grace.hill34@example.com', 4),
('Jack', 'Scott', 'Chestnut Ct', '35E', 2727, 'Elwood City', 'jack.scott35@example.com', 5),
('Chloe', 'Green', 'Beech St', '36F', 2828, 'Quahog', 'chloe.green36@example.com', 6),
('Levi', 'Adams', 'Hemlock Way', '37G', 2929, 'Springfield', 'levi.adams37@example.com', 7),
('Lily', 'Baker', 'Sequoia Ln', '38H', 3030, 'Riverdale', 'lily.baker38@example.com', 8),
('Julian', 'Gonzalez', 'Holly Dr', '39I', 3131, 'Gotham', 'julian.gonzalez39@example.com', 9),
('Zoey', 'Nelson', 'Cottonwood Ct', '40J', 3232, 'Metropolis', 'zoey.nelson40@example.com', 10),

('David', 'Carter', 'Olive St', '41A', 3333, 'Star City', 'david.carter41@example.com', 1),
('Nora', 'Mitchell', 'Mulberry Ave', '42B', 3434, 'Central City', 'nora.mitchell42@example.com', 2),
('Caleb', 'Perez', 'Laurel Rd', '43C', 3535, 'Smallville', 'caleb.perez43@example.com', 3),
('Hannah', 'Roberts', 'Alder Blvd', '44D', 3636, 'Coast City', 'hannah.roberts44@example.com', 4),
('Nathan', 'Turner', 'Cypress Dr', '45E', 3737, 'Hill Valley', 'nathan.turner45@example.com', 5),
('Sofia', 'Phillips', 'Elder Ct', '46F', 3838, 'Neo Tokyo', 'sofia.phillips46@example.com', 6),
('Christian', 'Campbell', 'Ironwood St', '47G', 3939, 'Liberty City', 'christian.campbell47@example.com', 7),
('Zoe', 'Parker', 'Mahogany Way', '48H', 4040, 'Los Santos', 'zoe.parker48@example.com', 8),
('Hunter', 'Evans', 'Tamarack Ln', '49I', 4141, 'Vice City', 'hunter.evans49@example.com', 9),
('Layla', 'Edwards', 'Yew Dr', '50J', 4242, 'Raccoon City', 'layla.edwards50@example.com', 10);